/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from "@react-three/fiber";
import { useLoader } from '@react-three/fiber';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader';

const Uzi = (props) =>{
    const gltf = useLoader(GLTFLoader, "/models/uzi.glb");

        const meshRef = useRef();
    
        useFrame(() =>{
            if(meshRef.current){
                meshRef.current.rotation.y +=0.01;

            }
        })

        // scale={0.3} position={[0,-1,0]} for scale and position if well.glb

    return (<primitive ref={meshRef} object={gltf.scene} /* paste here */  />);
}

export default Uzi;

// const Model = (props) => {

//   const { nodes, materials } = useGLTF("./models/uzi.glb")

//   return (

//     <group {...props} dispose={null}>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Cube001.geometry}
//         material={materials.Material}
//         position={[0, 0.615, -0.1]}
//         scale={[0.175, 0.25, 1.387]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Cylinder.geometry}
//         material={materials.Material}
//         position={[0, 0.814, 1.726]}
//         rotation={[Math.PI / 2, 0, 0]}
//         scale={[0.091, 0.09, 0.09]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Plane.geometry}
//         material={materials.Material}
//         position={[0.011, 0.005, 0]}
//         rotation={[0, 0, -Math.PI / 2]}
//         scale={[1, 1.348, 1]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Plane001.geometry}
//         material={materials.Material}
//         position={[0, 0.005, 0]}
//         rotation={[0, 0, -Math.PI / 2]}
//         scale={[1, 1.348, 1]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Plane002.geometry}
//         material={materials.Material}
//         position={[0, 0.268, 0.989]}
//         rotation={[0, 0, -Math.PI / 2]}
//         scale={[1, 1.348, 1]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Cube002.geometry}
//         material={materials.Material}
//         position={[0, 1.164, -0.007]}
//         scale={[0.097, 0.104, 0.882]}
//       />
//       <group position={[0.008, 0.917, 0]} scale={[0.156, 0.183, 1.276]}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes['Cube004-0'].geometry}
//           material={materials.Material}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes['Cube004-0_1'].geometry}
//           material={materials.Material}
//         />
//       </group>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Plane004.geometry}
//         material={materials.Material}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Plane005.geometry}
//         material={materials.Material}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Plane006.geometry}
//         material={materials.Material}
//         position={[0.096, 1.306, 1.159]}
//         scale={0.873}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Cube.geometry}
//         material={materials.Material}
//         position={[0, -1.126, -0.061]}
//         scale={[0.222, 0.346, 0.222]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Cylinder002.geometry}
//         material={materials.Material}
//         position={[0.13, 0.779, -0.058]}
//         rotation={[Math.PI / 2, 0, 0]}
//         scale={[0.054, 0.781, 0.049]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Cylinder001.geometry}
//         material={materials.Material}
//         position={[0.13, 0.911, -0.058]}
//         rotation={[Math.PI / 2, 0, 0]}
//         scale={[0.054, 0.781, 0.049]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Cube004.geometry}
//         material={materials.Material}
//         position={[0.009, 1.096, 0]}
//         scale={[0.187, 0.077, 0.941]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Cylinder003.geometry}
//         material={materials.Material}
//         position={[0.126, 1.06, 0.989]}
//         rotation={[Math.PI / 2, 0, 0]}
//         scale={[0.054, 0.044, 0.049]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Cylinder004.geometry}
//         material={materials.Material}
//         position={[0.16, 1.063, 0.607]}
//         scale={[1.347, 1, 1.019]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Cylinder005.geometry}
//         material={materials.Material}
//         position={[0.216, 1.06, 0.617]}
//         rotation={[0, 0, -Math.PI / 2]}
//         scale={0.092}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Cylinder006.geometry}
//         material={materials.Material}
//         position={[0.299, 1.065, 0.623]}
//         rotation={[0, 0, -1.553]}
//         scale={0.054}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Sphere.geometry}
//         material={materials.Material}
//         position={[0.377, 1.067, 0.623]}
//         rotation={[0, 0, -Math.PI / 2]}
//         scale={0.059}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Cylinder007.geometry}
//         material={materials.Material}
//         position={[0, 0.566, 0.658]}
//         rotation={[0, 0, -Math.PI / 2]}
//         scale={[0.032, 0.186, 0.032]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Cylinder008.geometry}
//         material={materials.Material}
//         position={[0.161, 0.546, 0.983]}
//         rotation={[0.775, 0, 0]}
//         scale={[0.018, 0.229, 0.011]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Cylinder009.geometry}
//         material={materials.Material}
//         position={[0, 0.566, 0.228]}
//         rotation={[0, 0, -Math.PI / 2]}
//         scale={[0.032, 0.186, 0.032]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Cylinder010.geometry}
//         material={materials.Material}
//         position={[0.161, 0.597, -0.668]}
//         rotation={[0.775, 0, 0]}
//         scale={[0.018, 0.161, 0.008]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Cylinder011.geometry}
//         material={materials.Material}
//         position={[0.161, 0.629, -1]}
//         rotation={[0.775, 0, 0]}
//         scale={[0.018, 0.112, 0.004]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Cylinder012.geometry}
//         material={materials.Material}
//         position={[0, 0.466, 1.115]}
//         rotation={[0, 0, -Math.PI / 2]}
//         scale={[0.07, 0.188, 0.07]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Cylinder014.geometry}
//         material={materials.Material}
//         position={[0, 0.484, -0.533]}
//         rotation={[0, 0, -Math.PI / 2]}
//         scale={[0.07, 0.188, 0.07]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Cylinder015.geometry}
//         material={materials.Material}
//         position={[-0.097, 1.317, -1.143]}
//         rotation={[0, 0, 1.571]}
//         scale={[0.096, 0.013, 0.096]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Cylinder013.geometry}
//         material={materials.Material}
//         position={[0.004, 1.051, -1.432]}
//         rotation={[0, 0, -Math.PI / 2]}
//         scale={[0.025, 0.172, 0.025]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Cylinder016.geometry}
//         material={materials.Material}
//         position={[0.004, 0.886, -1.432]}
//         rotation={[0, 0, -Math.PI / 2]}
//         scale={[0.025, 0.172, 0.025]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Cylinder017.geometry}
//         material={materials.Material}
//         position={[0.003, -0.005, 0.113]}
//         rotation={[0, 0, -Math.PI / 2]}
//         scale={[0.032, 0.162, 0.032]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Cylinder018.geometry}
//         material={materials.Material}
//         position={[0.003, -0.892, -0.413]}
//         rotation={[0, 0, -Math.PI / 2]}
//         scale={[0.032, 0.162, 0.032]}
//       />
//     </group>
//   )
// }

// useGLTF.preload('./models/uzi.glb')

// export default Model;
